name: ms-services
services:
  redis:
    image: redis:6.2.5
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - ms-service
networks:
  ms-service:
    name: ms-service